//! Public functions that nothing in the product calls (defects 65, 86, 91,
//! and HOST-05's tracing).
//!
//! Seven times in two days this project has shipped a correct, unit-tested
//! mechanism that nothing invokes: the assistant's tools with no endpoint to
//! construct them, a role source with nothing reading it, a JWT verifier no
//! handler calls, an operator key with no schema, and a trace exporter that
//! had never executed. Every one was found by a person happening to reach for
//! it. This is the mechanical version.
//!
//! **What it measures, exactly**, because a ratchet whose stated subject
//! exceeds its real one is worse than a narrow one — it stops people looking:
//!
//! * every `pub fn` in `impl AppState` and `impl Runtime`, the two types where
//!   the product is composed;
//! * every free `pub fn` and `pub async fn` directly in `routes/`.
//!
//! It does **not** reach other crates, other modules of this one, trait
//! methods, or inherent methods on any other type. `research::execute` was the
//! eighth instance of the defect above and sat outside this file's scope for a
//! day — a free function in `routes/`, which is why that case is now in. WP-25
//! found it by reading the agent's side, not from here.
//!
//! **It counts callers in production code only.** A test calling something is
//! not the product calling it — that is precisely how HOST-05's tracing came
//! to be marked done, by an acceptance test that built its own state and
//! called the exporter by hand. A version of this ratchet that accepted a test
//! as a caller would have passed on the same day.
//!
//! What an entry leaving `UNCALLED_TODAY` proves: some production code now
//! names that function. Not that the RIGHT code does, and not that the call is
//! correct. "Is it wired" becomes mechanical here; "is it wired correctly"
//! stays a reading job.

use std::collections::BTreeSet;
use std::path::{Path, PathBuf};

/// Every public function of `AppState` or `Runtime` with no caller outside
/// tests, each with the reason it is acceptable — or the defect it is.
///
/// A bare list of names becomes the thing nobody reads. Adding a row here is
/// a claim that somebody looked, so the claim is written down.
const UNCALLED_TODAY: &[(&str, &str)] = &[
    (
        "api::deprecation",
        "REST-11's `Deprecation`/`Sunset` announcement. Correct and uncalled: \
         no route is going away yet, so nothing has a sunset date to announce. \
         It is the kind of thing whose absence is only noticed by the reader \
         of a route that vanished, which is why it was written first.",
    ),
    (
        "export_once",
        "deliberate: the `once` variant exists so a test need not wait on the \
         five-second export timer. The loop is what production runs.",
    ),
    (
        "feedback::llms_txt_fragment",
        "RX-52. The fragment exists so the agent channel's description and its \
         route cannot disagree — but `llms.txt` is generated by `liyasa-build`, \
         which does not depend on this crate, so nothing here can hand it over. \
         The seam that would close it is WP-06's.",
    ),
    (
        "research::execute",
        "AGT-02's read tools, reported by WP-25 and the eighth instance of the \
         defect this file's doc opens with. The dispatch is written and tested; \
         no HTTP route reaches it. Being mounted in this packet — this row is \
         the one that should go first.",
    ),
    (
        "webhooks::verify",
        "REST-10's reference verification, deliberately. The doc comment says \
         it: `ours is the reference an operator copies`. The SERVER signs and \
         never verifies — a receiver does — so a caller here would mean this \
         server was checking its own signature.",
    ),
    (
        "with_limiter",
        "deliberate: a test-only builder. `main` configures pools through \
         `state.limiter.configure` instead, so there is nothing to replace.",
    ),
];

fn repo() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("..")
}

/// Source with comments and `#[cfg(test)]` modules removed, so a name that
/// appears only in a doc comment or only in a unit test does not read as a
/// caller. Both mistakes have already been made measuring this.
fn production_source() -> String {
    let mut out = String::new();
    let mut files = Vec::new();
    collect(&repo().join("crates"), &mut files);
    for file in files {
        let text = std::fs::read_to_string(&file).unwrap_or_default();
        out.push_str(&strip_test_modules(&strip_comments(&text)));
        out.push('\n');
    }
    out
}

fn collect(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            if path.file_name().is_some_and(|n| n == "target") {
                continue;
            }
            collect(&path, out);
        } else if path.extension().is_some_and(|e| e == "rs") {
            out.push(path);
        }
    }
}

fn strip_comments(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let mut chars = text.chars().peekable();
    let mut in_block = 0usize;
    let mut in_string = false;
    while let Some(c) = chars.next() {
        if in_block > 0 {
            if c == '*' && chars.peek() == Some(&'/') {
                chars.next();
                in_block -= 1;
            } else if c == '/' && chars.peek() == Some(&'*') {
                chars.next();
                in_block += 1;
            }
            continue;
        }
        if in_string {
            if c == '\\' {
                chars.next();
            } else if c == '"' {
                in_string = false;
            }
            out.push(c);
            continue;
        }
        match c {
            '"' => {
                in_string = true;
                out.push(c);
            }
            '/' if chars.peek() == Some(&'/') => {
                for c in chars.by_ref() {
                    if c == '\n' {
                        break;
                    }
                }
                out.push('\n');
            }
            '/' if chars.peek() == Some(&'*') => {
                chars.next();
                in_block = 1;
            }
            _ => out.push(c),
        }
    }
    out
}

/// Drops `#[cfg(test)] mod ... { .. }` by matching braces from the `mod`.
fn strip_test_modules(text: &str) -> String {
    let mut out = String::with_capacity(text.len());
    let mut rest = text;
    while let Some(at) = rest.find("#[cfg(test)]") {
        out.push_str(&rest[..at]);
        let after = &rest[at..];
        let Some(open) = after.find('{') else {
            break;
        };
        let mut depth = 0usize;
        let mut end = None;
        for (index, c) in after[open..].char_indices() {
            match c {
                '{' => depth += 1,
                '}' => {
                    depth -= 1;
                    if depth == 0 {
                        end = Some(open + index + 1);
                        break;
                    }
                }
                _ => {}
            }
        }
        match end {
            Some(end) => rest = &after[end..],
            None => return out,
        }
    }
    out.push_str(rest);
    out
}

/// The public functions declared in one `impl` block.
fn public_functions(source: &str, header: &str) -> Vec<String> {
    let Some(start) = source.find(header) else {
        panic!("`{header}` is not in that file any more; this ratchet is measuring nothing");
    };
    let body = &source[start + header.len()..];
    let mut depth = 1usize;
    let mut end = body.len();
    for (index, c) in body.char_indices() {
        match c {
            '{' => depth += 1,
            '}' => {
                depth -= 1;
                if depth == 0 {
                    end = index;
                    break;
                }
            }
            _ => {}
        }
    }
    let mut out = Vec::new();
    for line in body[..end].lines() {
        let line = line.trim();
        for prefix in ["pub fn ", "pub async fn "] {
            if let Some(rest) = line.strip_prefix(prefix)
                && let Some(name) = rest.split('(').next()
            {
                out.push(name.trim().to_owned());
            }
        }
    }
    out
}

/// Whether production code names this function at all.
///
/// Calls and **references** both count, because a handler is wired by being
/// passed rather than called — `get(health::health)` has no `health(` in it,
/// and neither does `JobKind::scheduled(DIGEST_JOB, digest_due, run_digest)`.
/// Counting only calls reported ten live functions as uncalled the first time
/// this file looked at free functions, every one of them a false positive.
///
/// Looser than a call check and deliberately so: the question this ratchet
/// asks is "does the product reach this", and for a function pointer the
/// reference IS the wiring.
fn has_production_caller(source: &str, name: &str) -> bool {
    if has_occurrence(source, name, "(") {
        return true;
    }
    // A reference: the name with a non-identifier character after it, so
    // `digest_due` does not match `digest_due_at`.
    for terminator in [",", ")", ";", " ", "\n"] {
        if has_occurrence(source, name, terminator) {
            return true;
        }
    }
    false
}

fn has_occurrence(source: &str, name: &str, after: &str) -> bool {
    let needle = format!("{name}{after}");
    let mut from = 0;
    while let Some(at) = source[from..].find(&needle) {
        let absolute = from + at;
        let before = source[..absolute].trim_end();
        let is_definition = before.ends_with("fn");
        let preceded_by_ident = source[..absolute]
            .chars()
            .next_back()
            .is_some_and(|c| c.is_alphanumeric() || c == '_');
        if !is_definition && !preceded_by_ident {
            return true;
        }
        from = absolute + needle.len();
    }
    false
}

/// Free `pub fn` and `pub async fn` declared directly in `routes/`.
///
/// A handler reached only by `.route(..)` is named there and so has a caller;
/// what this catches is the module that was written, tested, and never
/// composed — `research::execute` was exactly that.
fn free_functions_in_routes() -> Vec<(String, String, String)> {
    let mut names = Vec::new();
    let dir = repo().join("crates/liyasa-server/src/routes");
    let Ok(entries) = std::fs::read_dir(&dir) else {
        panic!(
            "{} is not readable; this ratchet measures nothing",
            dir.display()
        );
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.extension().and_then(|e| e.to_str()) != Some("rs") {
            continue;
        }
        let Some(stem) = path.file_stem().and_then(|s| s.to_str()).map(str::to_owned) else {
            continue;
        };
        if stem == "mod" {
            continue;
        }
        let text = std::fs::read_to_string(&path).unwrap_or_default();
        let stripped = strip_test_modules(&strip_comments(&text));
        for line in stripped.lines() {
            // Only column zero: an indented `pub fn` is a method on some
            // impl, which is a different subject and not this one's.
            let Some(rest) = line
                .strip_prefix("pub async fn ")
                .or_else(|| line.strip_prefix("pub fn "))
            else {
                continue;
            };
            let name: String = rest
                .chars()
                .take_while(|c| c.is_alphanumeric() || *c == '_')
                .collect();
            if !name.is_empty() {
                names.push((stem.clone(), name, stripped.clone()));
            }
        }
    }
    names
}

fn uncalled() -> BTreeSet<String> {
    let source = production_source();
    let mod_rs = std::fs::read_to_string(repo().join("crates/liyasa-server/src/routes/mod.rs"))
        .expect("routes/mod.rs");
    let serve_rs = std::fs::read_to_string(repo().join("crates/liyasa-server/src/routes/serve.rs"))
        .expect("routes/serve.rs");

    let mut names = public_functions(&mod_rs, "impl AppState {");
    names.extend(public_functions(&serve_rs, "impl Runtime {"));
    assert!(
        names.len() > 20,
        "only {} public functions found; the parser has stopped matching and \
         an empty result would read as a clean bill of health",
        names.len()
    );

    let mut out: BTreeSet<String> = names
        .into_iter()
        .filter(|name| !has_production_caller(&source, name))
        .collect();

    // A free function is checked by its QUALIFIED path. `execute` alone
    // matches `tx.execute(` in the store and `deprecation` matches a field —
    // short names collide, and a collision here reads as "something calls
    // this", which is the direction that hides the defect.
    for (module, name, own_file) in free_functions_in_routes() {
        // Two ways a free function is reached, and both count: named from
        // another module as `module::name`, or used bare inside its own file.
        // Checking only the qualified form reported twenty-one functions as
        // uncalled when one was — `JobKind::scheduled(RETENTION_JOB,
        // retention_due, run_retention)` sits in the module that defines them.
        let qualified = source.contains(&format!("{module}::{name}"));
        let within = has_production_caller(&own_file, &name);
        if !qualified && !within {
            out.insert(format!("{module}::{name}"));
        }
    }
    out
}

#[test]
fn nothing_new_is_built_without_a_caller() {
    let found = uncalled();
    let pinned: BTreeSet<String> = UNCALLED_TODAY
        .iter()
        .map(|(name, _)| (*name).to_owned())
        .collect();
    assert_eq!(
        found, pinned,
        "\nthe set of public functions with no production caller changed.\n\
         If it GREW, something was built that nothing invokes — wire it, or \
         add a row to UNCALLED_TODAY saying why it is deliberate.\n\
         If it SHRANK, delete the row: its entry leaving this list is the \
         proof that the wiring landed.\n"
    );
}

#[test]
fn every_pinned_entry_carries_a_reason_somebody_wrote() {
    for (name, reason) in UNCALLED_TODAY {
        assert!(
            reason.len() > 40,
            "`{name}` has no real reason, and a bare list is the thing nobody \
             reads"
        );
    }
    let mut names: Vec<&str> = UNCALLED_TODAY.iter().map(|(name, _)| *name).collect();
    let sorted = {
        let mut copy = names.clone();
        copy.sort_unstable();
        copy
    };
    assert_eq!(names, sorted, "UNCALLED_TODAY is not sorted");
    names.dedup();
    assert_eq!(names.len(), UNCALLED_TODAY.len(), "a name is pinned twice");
}

#[test]
fn a_test_only_caller_does_not_count_as_a_caller() {
    // The property the whole ratchet rests on, and the one that would have
    // caught HOST-05: an acceptance test calling something is not the product
    // calling it. `with_limiter` is called by tests/src/server.rs and by
    // nothing else, so if this ever fails the source filter has stopped
    // excluding tests and the ratchet is worthless.
    //
    // It used to name `with_tracer`, which was a defect rather than a
    // deliberate test-only builder. That entry left the list when the binary
    // started enabling the tracer, which is what an entry leaving is supposed
    // to mean.
    let source = production_source();
    assert!(
        !has_production_caller(&source, "with_limiter"),
        "`with_limiter` reads as called from production, so either it gained a \
         real caller — delete its row and pick another test-only function for \
         this assertion — or the filter is broken"
    );
}

// ---- the same shape, one level up: a surface declared and never mounted ----

/// Every `/_liyasa/` prefix `pool_for` claims that no route answers, with the
/// reason it is acceptable — or the defect it is.
///
/// `pool_for` maps a request path to a rate-limit bucket, and it is the
/// closest thing the server has to a list of its own surfaces: complete and
/// current for everything that does exist, and nobody adds a limiter bucket
/// speculatively. That is exactly what makes it dangerous — it is a list of
/// intentions that reads as a list of facts, and four entries sat in it for
/// weeks pointing at nothing (defect 150). Each has its mechanism built and
/// unit-tested; what is missing is the route.
///
/// Empty since defect 146 closed: `crate::assistant::http` serves
/// `/_liyasa/assistant` and builds the `ReaderContext` that was previously
/// constructed only in tests.
///
/// **What that does not prove is what this census cannot see.** A `.route(`
/// literal existing is not `routes::application` composing it, and the
/// subtree line lives in `routes/mount.rs`. The other half is
/// `ast_11_assistant_endpoint::the_application_the_binary_runs_serves_the_assistant_endpoint`,
/// which asks the composed object and skips with its reason while that line is
/// absent.
const UNROUTED_TODAY: &[(&str, &str)] = &[];

/// The `starts_with("/_liyasa/...")` prefixes `pool_for` claims.
///
/// Scoped to that function by brace matching: `pool_name` below it matches on
/// the same paths for its metric label, and counting those would double every
/// prefix.
fn pool_prefixes(mod_rs: &str) -> BTreeSet<String> {
    const HEADER: &str = "pub fn pool_for(";
    let start = mod_rs
        .find(HEADER)
        .expect("`pool_for` is not in routes/mod.rs any more; this ratchet measures nothing");
    let body = &mod_rs[start..];
    let open = body.find('{').expect("a body");
    let mut depth = 0usize;
    let mut end = body.len();
    for (index, c) in body[open..].char_indices() {
        match c {
            '{' => depth += 1,
            '}' => {
                depth -= 1;
                if depth == 0 {
                    end = open + index;
                    break;
                }
            }
            _ => {}
        }
    }
    let mut out = BTreeSet::new();
    let mut rest = &body[open..end];
    while let Some(at) = rest.find("starts_with(\"") {
        let after = &rest[at + "starts_with(\"".len()..];
        if let Some(close) = after.find('"') {
            let path = &after[..close];
            if path.starts_with("/_liyasa/") {
                out.insert(path.to_owned());
            }
            rest = &after[close..];
        } else {
            break;
        }
    }
    out
}

/// Every path handed to `.route(`, across the crate.
///
/// Reads the first string literal after each `.route(` rather than matching
/// `.route("..."` on one line: `/_liyasa/e` is mounted with its path on its
/// own line, and a single-line pattern reports it as unrouted. That mistake
/// was made while writing this.
fn mounted_paths(source: &str) -> BTreeSet<String> {
    let mut out = BTreeSet::new();
    let mut rest = source;
    while let Some(at) = rest.find(".route(") {
        let after = &rest[at + ".route(".len()..];
        let Some(open) = after.find('"') else {
            rest = after;
            continue;
        };
        let literal = &after[open + 1..];
        match literal.find('"') {
            Some(close) => {
                out.insert(literal[..close].to_owned());
                rest = &literal[close..];
            }
            None => break,
        }
    }
    out
}

fn server_source() -> String {
    let mut out = String::new();
    let mut files = Vec::new();
    collect(&repo().join("crates/liyasa-server/src"), &mut files);
    for file in files {
        let text = std::fs::read_to_string(&file).unwrap_or_default();
        out.push_str(&strip_test_modules(&strip_comments(&text)));
        out.push('\n');
    }
    out
}

#[test]
fn the_route_census_is_not_defeated_by_a_nested_router() {
    // `mounted_paths` reads `.route(` calls. A `nest()` would mount a whole
    // subtree under a prefix that never appears in one, and every assertion
    // below would then be measuring a list it cannot see. There is no nesting
    // in this crate today; if that changes, this ratchet has to learn about it
    // before it can be trusted again.
    let source = server_source();
    for needle in [".nest(", ".nest_service("] {
        assert!(
            !source.contains(needle),
            "`{needle}` appeared in liyasa-server. `mounted_paths` cannot see routes mounted \
             that way, so the unrouted-pool ratchet is now measuring less than it claims. \
             Teach it to resolve the prefix before removing this assertion."
        );
    }
}

#[test]
fn no_pool_claims_a_surface_that_nothing_serves() {
    let mod_rs = std::fs::read_to_string(repo().join("crates/liyasa-server/src/routes/mod.rs"))
        .expect("routes/mod.rs");
    let prefixes = pool_prefixes(&mod_rs);
    assert!(
        prefixes.len() >= 5,
        "only {} pool prefixes parsed out of `pool_for`; the parser has stopped matching \
         and an empty result would read as a clean bill of health",
        prefixes.len()
    );

    let mounted = mounted_paths(&server_source());
    assert!(
        mounted.iter().any(|path| path == "/_liyasa/e"),
        "`/_liyasa/e` is mounted across several lines and is the case that proves \
         `mounted_paths` reads more than one-line `.route(\"...\")` calls; it is missing, \
         so the census is wrong"
    );

    let unrouted: BTreeSet<String> = prefixes
        .into_iter()
        .filter(|prefix| !mounted.iter().any(|path| path.starts_with(prefix)))
        .collect();
    let pinned: BTreeSet<String> = UNROUTED_TODAY
        .iter()
        .map(|(path, _)| (*path).to_owned())
        .collect();
    assert_eq!(
        unrouted, pinned,
        "\nthe set of rate-limit pools with no route changed.\n\
         If it GREW, a pool was added for a surface nobody mounted — mount it, or add a \
         row to UNROUTED_TODAY saying why the bucket exists without the endpoint.\n\
         If it SHRANK, delete the row: the entry leaving this list is the proof that the \
         endpoint landed.\n"
    );
}

#[test]
fn every_unrouted_pool_carries_a_reason_somebody_wrote() {
    for (path, reason) in UNROUTED_TODAY {
        assert!(
            reason.len() > 40,
            "`{path}` is pinned with a reason too short to have been thought about: {reason}"
        );
    }
}
