//! `THIRD_PARTY_LICENSES.md`, generated (NFR-15).
//!
//! Two populations end up in one file because a reader wants one page. Crates
//! come from `cargo metadata`, which knows the resolved graph and each
//! package's declared licence; the non-crate assets — fonts, icon sets,
//! grammars, dictionaries — come from `xtask/assets.toml`, because nothing in
//! the build graph knows a font exists.
//!
//! TODO(rfc-3200): NFR-15 names `cargo about` for this file. It reads the crate
//! graph, and half of what the same sentence asks it to publish — the fonts,
//! the icon sets, the grammars, the dictionaries — is not in any graph. The RFC
//! records the substitution; `cargo deny check licenses` is untouched.
//!
//! The asset half is checked without running anything: the section between the
//! two markers below is a pure function of the inventory, so
//! [`asset_section_matches`] compares strings and runs in a test. The crate
//! half needs the resolver, so it is regenerated by `xtask notices` and checked
//! in CI with `git diff --exit-code`, the same way the generated schemas are.

use std::fmt::Write as _;
use std::path::Path;

use crate::licences::{self, Asset};

pub const FILE: &str = "THIRD_PARTY_LICENSES.md";

/// The asset table lives between these, so the half that can be checked
/// offline can be found without parsing Markdown.
pub const ASSETS_BEGIN: &str = "<!-- assets: generated from xtask/assets.toml -->";
pub const ASSETS_END: &str = "<!-- end assets -->";

/// One package of the resolved graph.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct Crate {
    pub name: String,
    pub version: String,
    /// The SPDX expression the package declares, or `None` where it declares
    /// none — which `cargo deny` treats as a failure and this file must not
    /// silently render as blank.
    pub licence: Option<String>,
}

/// The resolved dependency graph, minus this workspace's own crates.
///
/// `cargo metadata` rather than a lock-file reader: the lock records versions
/// and not licences, and the licence is the only thing this file is about.
pub fn crates(root: &Path) -> Result<Vec<Crate>, String> {
    let output = std::process::Command::new(std::env::var("CARGO").unwrap_or("cargo".to_owned()))
        .current_dir(root)
        .args(["metadata", "--format-version", "1", "--all-features"])
        .output()
        .map_err(|e| format!("cargo metadata: {e}"))?;
    if !output.status.success() {
        return Err(format!(
            "cargo metadata: {}",
            String::from_utf8_lossy(&output.stderr).trim()
        ));
    }
    let json: serde_json::Value =
        serde_json::from_slice(&output.stdout).map_err(|e| format!("cargo metadata: {e}"))?;
    from_metadata(&json)
}

/// The parsing half, split out so a test can drive it without a subprocess.
pub fn from_metadata(json: &serde_json::Value) -> Result<Vec<Crate>, String> {
    let members: Vec<&str> = json
        .get("workspace_members")
        .and_then(serde_json::Value::as_array)
        .ok_or("cargo metadata has no workspace_members")?
        .iter()
        .filter_map(serde_json::Value::as_str)
        .collect();
    let packages = json
        .get("packages")
        .and_then(serde_json::Value::as_array)
        .ok_or("cargo metadata has no packages")?;

    let mut out: Vec<Crate> = packages
        .iter()
        .filter(|package| {
            package
                .get("id")
                .and_then(serde_json::Value::as_str)
                .is_none_or(|id| !members.contains(&id))
        })
        .filter_map(|package| {
            Some(Crate {
                name: package.get("name")?.as_str()?.to_owned(),
                version: package.get("version")?.as_str()?.to_owned(),
                licence: package
                    .get("license")
                    .and_then(serde_json::Value::as_str)
                    .map(str::to_owned),
            })
        })
        .collect();
    out.sort();
    out.dedup();
    if out.len() < 20 {
        return Err(format!("only {} third-party crates parsed", out.len()));
    }
    Ok(out)
}

/// The whole file.
pub fn render(assets: &[Asset], crates: &[Crate]) -> String {
    let mut out = String::from(
        "# Third-party licences\n\
         \n\
         Liyasa ships other people's work. This file lists it: the crates it is \
         built from, and the fonts, icon sets, grammars and dictionaries it \
         bundles or downloads.\n\
         \n\
         It is generated. Run `cargo run -p xtask -- notices` and commit the \
         result; the crate rows come from the resolved dependency graph and the \
         asset rows from `xtask/assets.toml`, which is transcribed from the \
         requirements' own inventory.\n\
         \n\
         The licences Liyasa accepts are a fixed list, enforced by \
         `cargo deny check licenses` on every pull request. \
         `cargo run -p xtask -- licences` enforces the other direction: that the \
         list `cargo deny` is given is still the list the requirements name.\n\
         \n",
    );
    out.push_str(&asset_section(assets));
    out.push('\n');
    out.push_str(&crate_section(crates));
    out
}

pub fn asset_section(assets: &[Asset]) -> String {
    let mut out = format!(
        "## Assets\n\
         \n\
         `Shipped` is whether the file travels in a Liyasa release. A row that \
         is not shipped is fetched at run time and its licence is shown and \
         accepted at the download.\n\
         \n\
         {ASSETS_BEGIN}\n\
         \n\
         | Asset | Source | Licence | Shipped | Licence text |\n\
         |---|---|---|---|---|\n"
    );
    for asset in assets {
        let notice = asset
            .notice
            .as_deref()
            .map_or_else(|| "—".to_owned(), |path| format!("`{path}`"));
        let _ = writeln!(
            out,
            "| {} | {} | {} | {} | {notice} |",
            asset.name,
            asset.source,
            asset.licence,
            if asset.bundled { "yes" } else { "on demand" },
        );
    }
    let _ = write!(out, "\n{ASSETS_END}\n");
    out
}

fn crate_section(crates: &[Crate]) -> String {
    let mut out = format!(
        "## Crates\n\
         \n\
         {} packages in the resolved graph, this workspace's own excluded. The \
         graph is resolved for every target and feature, so a crate here may \
         not be in any particular build.\n\
         \n\
         | Crate | Version | Licence |\n\
         |---|---|---|\n",
        crates.len()
    );
    for package in crates {
        let _ = writeln!(
            out,
            "| {} | {} | {} |",
            package.name,
            package.version,
            // A package that declares nothing says so rather than rendering an
            // empty cell that reads like a licence nobody bothered to fill in.
            package.licence.as_deref().unwrap_or("**none declared**"),
        );
    }
    out
}

/// The asset table the inventory implies, and the one the committed file has.
pub fn asset_section_matches(root: &Path) -> Result<Option<String>, String> {
    let path = root.join(FILE);
    let text = std::fs::read_to_string(&path).map_err(|e| format!("{}: {e}", path.display()))?;
    let want = asset_section(&licences::inventory(root)?);
    let (Some(begin), Some(end)) = (text.find(ASSETS_BEGIN), text.find(ASSETS_END)) else {
        return Ok(Some(format!("{FILE} has no asset section markers")));
    };
    let have = &text[begin..end + ASSETS_END.len()];
    let want_inner = want
        .find(ASSETS_BEGIN)
        .map(|at| &want[at..])
        .unwrap_or(&want)
        .trim_end();
    if have.trim_end() == want_inner {
        return Ok(None);
    }
    Ok(Some(format!(
        "{FILE}'s asset table is not what xtask/assets.toml says.\n\
         Run `cargo run -p xtask -- notices` and commit the result."
    )))
}

/// Regenerates the file.
pub fn run(root: &Path) -> Result<(), String> {
    let assets = licences::inventory(root)?;
    let crates = crates(root)?;
    let path = root.join(FILE);
    std::fs::write(&path, render(&assets, &crates))
        .map_err(|e| format!("{}: {e}", path.display()))?;
    println!(
        "wrote {} with {} crates and {} assets",
        path.display(),
        crates.len(),
        assets.len()
    );
    Ok(())
}
