//! MIG-02. Given a Docusaurus project whose config and sidebars are literal
//! objects, with MDX, admonitions, versions, i18n, and the client-redirects
//! plugin; when it is imported; then the config and navigation are produced,
//! the four components MIG-02 names are mapped, versions and locales carry,
//! redirects carry, and a config that is not a literal object asks for the Node
//! script instead of guessing.

use liyasa_config::vfs::MemVfs;
use liyasa_core::vfs::VfsPath;
use liyasa_import::docusaurus;

use crate::support::{Builtins, config, pages_scan, paths, text_at, validate};

const CONFIG: &str = r#"
const lightCodeTheme = { plain: {} };

const config = {
  title: 'Acme',
  tagline: 'Docs that work',
  favicon: 'img/favicon.ico',
  url: 'https://acme.example',
  baseUrl: '/',
  organizationName: 'acme',
  projectName: 'docs',
  onBrokenLinks: 'throw',
  i18n: { defaultLocale: 'en', locales: ['en', 'de'] },
  presets: [
    ['classic', {
      docs: { sidebarPath: './sidebars.js', routeBasePath: 'docs' },
      theme: { customCss: './src/css/custom.css' },
    }],
  ],
  plugins: [
    ['@docusaurus/plugin-client-redirects', {
      redirects: [{ to: '/docs/intro', from: ['/welcome', '/start'] }],
    }],
  ],
  themeConfig: {
    navbar: {
      title: 'Acme',
      logo: { alt: 'Acme', src: 'img/logo.svg', srcDark: 'img/logo-dark.svg' },
      items: [
        { type: 'docSidebar', sidebarId: 'tutorialSidebar', position: 'left', label: 'Tutorial' },
        { href: 'https://github.com/acme/docs', label: 'GitHub', position: 'right' },
      ],
    },
    footer: {
      style: 'dark',
      links: [{ title: 'Docs', items: [{ label: 'Tutorial', to: '/docs/intro' }] }],
      copyright: 'Copyright Acme.',
    },
    colorMode: { defaultMode: 'dark', disableSwitch: false },
    prism: { theme: lightCodeTheme },
  },
};

export default config;
"#;

const SIDEBARS: &str = r#"
module.exports = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      link: { type: 'doc', id: 'guides/index' },
      items: ['guides/install', { type: 'doc', id: 'guides/deploy' }],
    },
    { type: 'link', label: 'Changelog', href: 'https://acme.example/changelog' },
    { type: 'autogenerated', dirName: 'reference' },
  ],
};
"#;

const INTRO: &str = "---\ntitle: Intro\nsidebar_label: Getting started\nsidebar_position: 1\n---\n\nimport Tabs from '@theme/Tabs';\nimport TabItem from '@theme/TabItem';\n\n# Intro\n\n:::tip Pro tip\nRun it twice.\n:::\n\n:::caution\nMind the gap.\n:::\n\n<Tabs groupId=\"pm\">\n  <TabItem value=\"npm\" label=\"npm\" default>\n    npm i acme\n  </TabItem>\n  <TabItem value=\"pnpm\" label=\"pnpm\">\n    pnpm add acme\n  </TabItem>\n</Tabs>\n";

const INSTALL: &str = "---\ntitle: Install\n---\n\nimport CodeBlock from '@theme/CodeBlock';\n\n<CodeBlock language=\"bash\" title=\"install.sh\">\nnpm i acme\n</CodeBlock>\n\n<Admonition type=\"danger\" title=\"Careful\">\nThis deletes things.\n</Admonition>\n";

fn project() -> MemVfs {
    MemVfs::new()
        .with("docusaurus.config.js", CONFIG.as_bytes().to_vec())
        .with("sidebars.js", SIDEBARS.as_bytes().to_vec())
        .with("docs/intro.md", INTRO.as_bytes().to_vec())
        .with("docs/guides/install.mdx", INSTALL.as_bytes().to_vec())
        .with(
            "docs/guides/index.md",
            "---\ntitle: Guides\n---\n\nGuides.\n".as_bytes().to_vec(),
        )
        .with(
            "docs/guides/deploy.md",
            "---\ntitle: Deploy\n---\n\nDeploy.\n".as_bytes().to_vec(),
        )
        .with(
            "docs/reference/api.md",
            "---\ntitle: API\n---\n\nAPI.\n".as_bytes().to_vec(),
        )
        .with("static/img/logo.svg", b"<svg/>".to_vec())
        .with("static/img/favicon.ico", b"icon".to_vec())
        .with("src/css/custom.css", b":root{}".to_vec())
        .with("src/pages/index.js", b"export default () => null".to_vec())
        .with(
            "versioned_docs/version-1.0/intro.md",
            "---\ntitle: Intro\n---\n\nOld.\n".as_bytes().to_vec(),
        )
        .with("versions.json", b"[\"1.0\"]".to_vec())
        .with(
            "i18n/de/docusaurus-plugin-content-docs/current/intro.md",
            "---\ntitle: Einleitung\n---\n\nHallo.\n"
                .as_bytes()
                .to_vec(),
        )
        .with("package.json", b"{}".to_vec())
}

fn import(vfs: &MemVfs) -> liyasa_import::Plan {
    docusaurus::import(
        vfs,
        &VfsPath::new(""),
        &docusaurus::Options {
            components: &Builtins::default(),
            directives: false,
        },
    )
}

#[test]
fn a_literal_config_is_read_in_process() {
    let plan = import(&project());
    assert!(
        plan.report.diagnostics.is_empty(),
        "{:?}",
        plan.report
            .diagnostics
            .iter()
            .map(|d| format!("{}: {}", d.code, d.message))
            .collect::<Vec<_>>()
    );
    let config = config(&plan);
    assert_eq!(config["name"], "Acme");
    assert_eq!(config["description"], "Docs that work");
    assert_eq!(config["seo"]["canonicalOrigin"], "https://acme.example");
    assert_eq!(config["favicon"]["light"], "/img/favicon.ico");
    assert_eq!(config["logo"]["light"], "/img/logo.svg");
    assert_eq!(config["logo"]["dark"], "/img/logo-dark.svg");
    assert_eq!(config["theme"]["appearance"]["default"], "dark");
    assert_eq!(config["theme"]["css"], "/src/css/custom.css");
    assert_eq!(config["navbar"]["links"][0]["label"], "GitHub");
    assert_eq!(config["footer"]["links"][0]["header"], "Docs");
    assert_eq!(config["footer"]["text"], "Copyright Acme.");
}

#[test]
fn locales_and_versions_are_declared() {
    let plan = import(&project());
    let config = config(&plan);
    assert_eq!(config["locales"][0]["code"], "en");
    assert_eq!(config["locales"][0]["default"], true);
    assert_eq!(config["locales"][1]["code"], "de");
    assert_eq!(config["versions"][1]["name"], "1.0");
}

#[test]
fn the_redirects_plugin_becomes_config_redirects() {
    let plan = import(&project());
    let config = config(&plan);
    let rules = config["redirects"].as_array().expect("redirect rules");
    assert_eq!(rules.len(), 2);
    assert_eq!(rules[0]["source"], "/welcome");
    assert_eq!(rules[0]["destination"], "/docs/intro");
    assert_eq!(rules[1]["source"], "/start");
}

#[test]
fn the_sidebar_becomes_the_navigation_with_doc_ids_as_page_paths() {
    let plan = import(&project());
    let config = config(&plan);
    let nav = &config["navigation"];

    assert_eq!(nav[0], "docs/intro");
    assert_eq!(nav[1]["group"], "Guides");
    assert_eq!(nav[1]["expanded"], true);
    assert_eq!(nav[1]["root"], "docs/guides/index");
    assert_eq!(nav[1]["pages"][0], "docs/guides/install");
    assert_eq!(nav[1]["pages"][1], "docs/guides/deploy");
    assert_eq!(nav[2]["anchor"], "Changelog");
    assert_eq!(nav[2]["href"], "https://acme.example/changelog");
    assert_eq!(nav[3]["directory"], "docs/reference");
}

#[test]
fn admonitions_gain_the_title_prop_and_caution_becomes_warning() {
    let plan = import(&project());
    let intro = text_at(&plan, "docs/intro.md");
    assert!(intro.contains(":::tip{title=\"Pro tip\"}"), "{intro}");
    assert!(intro.contains(":::warning\n"), "{intro}");
    assert!(!intro.contains(":::caution"));
}

#[test]
fn tabs_and_tab_items_are_mapped_at_both_ends() {
    let plan = import(&project());
    let intro = text_at(&plan, "docs/intro.md");
    assert!(intro.contains("<Tabs>"), "{intro}");
    assert!(
        !intro.contains("groupId"),
        "a Docusaurus-only prop survived"
    );
    assert!(
        intro.contains("<Tab title=\"npm\" default=true>"),
        "{intro}"
    );
    assert!(intro.contains("</Tab>"), "{intro}");
    assert!(!intro.contains("TabItem"), "{intro}");
}

#[test]
fn a_code_block_component_becomes_a_fence() {
    let plan = import(&project());
    let install = text_at(&plan, "docs/guides/install.md");
    assert!(
        install.contains("```bash {title=\"install.sh\"}"),
        "{install}"
    );
    assert!(install.contains("npm i acme\n```"), "{install}");
    assert!(!install.contains("CodeBlock"), "{install}");
}

#[test]
fn an_admonition_component_becomes_its_callout() {
    let plan = import(&project());
    let install = text_at(&plan, "docs/guides/install.md");
    assert!(install.contains("<Danger title=\"Careful\">"), "{install}");
    assert!(install.contains("</Danger>"), "{install}");
}

#[test]
fn theme_imports_cost_the_page_nothing() {
    let plan = import(&project());
    for page in &plan.report.pages {
        assert!(
            page.is_clean(),
            "{} was not clean: {:?}",
            page.from,
            page.attention
        );
    }
}

#[test]
fn pages_land_where_their_docusaurus_url_says() {
    let plan = import(&project());
    let paths = paths(&plan);
    assert!(paths.contains(&"docs/intro.md"), "{paths:?}");
    assert!(paths.contains(&"docs/guides/install.md"));
    assert!(paths.contains(&"versions/1.0/docs/intro.md"), "{paths:?}");
    assert!(paths.contains(&"locales/de/docs/intro.md"), "{paths:?}");
    for page in &plan.report.pages {
        if page.from.as_str().starts_with("versioned_docs/") {
            continue;
        }
        assert!(
            !page.moved(),
            "{} moved from {} to {}",
            page.from,
            page.old_route,
            page.route
        );
    }
}

#[test]
fn an_archived_version_changes_route_and_gets_a_redirect() {
    let plan = import(&project());
    let archived = plan
        .report
        .pages
        .iter()
        .find(|page| page.from.as_str() == "versioned_docs/version-1.0/intro.md")
        .expect("the archived page is in the report");
    assert_eq!(archived.old_route, "/docs/1.0/intro");
    assert_eq!(archived.route, "/1.0/docs/intro");
    assert!(archived.moved());
    assert!(
        plan.report
            .redirects
            .iter()
            .any(|rule| rule.source == "/docs/1.0/intro"),
        "MIG-05 generates a redirect when the structure changes: {:?}",
        plan.report.redirects
    );
}

#[test]
fn the_unversioned_tree_is_the_default_version() {
    let plan = import(&project());
    let config = config(&plan);
    assert_eq!(config["versions"][0]["name"], "current");
    assert_eq!(config["versions"][0]["default"], true);
    assert_eq!(config["versions"][1]["name"], "1.0");
    assert_eq!(config["versions"][1]["path"], "versions/1.0");
}

#[test]
fn the_static_directory_becomes_the_project_root() {
    let plan = import(&project());
    let paths = paths(&plan);
    assert!(paths.contains(&"img/logo.svg"), "{paths:?}");
    assert!(!paths.iter().any(|path| path.starts_with("static/")));
    assert!(paths.contains(&"src/css/custom.css"));
    assert!(!paths.contains(&"package.json"));
    assert!(!paths.contains(&"sidebars.js"));
}

#[test]
fn a_react_page_is_reported_rather_than_carried_or_dropped_in_silence() {
    let plan = import(&project());
    let named: Vec<&str> = plan
        .report
        .attention
        .iter()
        .map(|item| item.what.as_str())
        .collect();
    assert!(named.contains(&"src/pages/index.js"), "{named:?}");
    assert!(!paths(&plan).contains(&"src/pages/index.js"));
}

#[test]
fn front_matter_is_renamed_and_the_sidebar_position_is_consumed() {
    let plan = import(&project());
    let intro = text_at(&plan, "docs/intro.md");
    assert!(intro.contains("sidebarTitle: Getting started"), "{intro}");
    assert!(!intro.contains("sidebar_position"), "{intro}");
}

#[test]
fn the_imported_project_loads_and_validates() {
    let source = project();
    let plan = import(&source);
    let problems = validate(&plan, &source);
    assert!(problems.is_empty(), "{problems:?}");
    pages_scan(&plan);
}

#[test]
fn a_config_that_is_not_a_literal_object_asks_for_the_node_script() {
    let vfs = MemVfs::new()
        .with(
            "docusaurus.config.js",
            b"const { themes } = require('prism-react-renderer');\n\
              module.exports = { title: 'Acme', theme: themes.github };\n"
                .to_vec(),
        )
        .with("docs/intro.md", b"# Intro\n".to_vec());
    let plan = import(&vfs);

    assert_eq!(
        plan.report
            .diagnostics
            .iter()
            .map(|d| d.code.as_str())
            .collect::<Vec<_>>(),
        ["E1105"]
    );
    let script = text_at(&plan, "liyasa-export-config.mjs");
    assert_eq!(script.lines().count(), 1, "{script}");
    assert!(
        plan.report
            .diagnostics
            .iter()
            .any(|d| d.help.as_deref().is_some_and(|h| h.contains("node "))),
        "the diagnostic does not say how to run the script"
    );
}

#[test]
fn a_config_exported_as_json_by_that_script_is_read_on_the_next_run() {
    let vfs = MemVfs::new()
        .with(
            "docusaurus.config.js",
            b"module.exports = { title: 'ignored', theme: broken.value };".to_vec(),
        )
        .with(
            "docusaurus.config.json",
            br#"{ "title": "Acme", "presets": [["classic", { "docs": { "routeBasePath": "/" } }]] }"#
                .to_vec(),
        )
        .with("docs/intro.md", b"---\ntitle: Intro\n---\n\nHi.\n".to_vec());
    let plan = import(&vfs);

    assert!(plan.report.diagnostics.is_empty());
    assert_eq!(config(&plan)["name"], "Acme");
    assert!(
        paths(&plan).contains(&"intro.md"),
        "routeBasePath `/` should put the page at the root: {:?}",
        paths(&plan)
    );
}

#[test]
fn a_directory_that_is_not_a_docusaurus_project_is_a_diagnostic_not_a_panic() {
    let plan = import(&MemVfs::new().with("README.md", b"# Nothing".to_vec()));
    assert_eq!(
        plan.report
            .diagnostics
            .iter()
            .map(|d| d.code.as_str())
            .collect::<Vec<_>>(),
        ["E1101"]
    );
}
